# Generated by Django 5.0.6 on 2024-06-08 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
