# Generated by Django 5.0.6 on 2024-06-08 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customer_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
