# Generated by Django 5.0.6 on 2024-06-09 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def add_unique_constraint(apps, schema_editor):
    Customer = apps.get_model('main', 'Customer')
    schema_editor.execute(
        'ALTER TABLE main_customer ADD CONSTRAINT main_customer_Customer_name_d2d114d5_uniq UNIQUE (Customer_name);'
    )

def remove_unique_constraint(apps, schema_editor):
    schema_editor.execute(
        'ALTER TABLE main_customer DROP INDEX main_customer_Customer_name_d2d114d5_uniq;'
    )
class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
